version: '3.8'
services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - PEER_ADDRESSES=node2:50052,node3:50053,node4:50054,node5:50055
    ports:
      - "50051:50051"

  node2:
    build: .
    environment:
      - NODE_ID=2
      - PEER_ADDRESSES=node1:50051,node3:50053,node4:50054,node5:50055
    ports:
      - "50052:50052"

  node3:
    build: .
    environment:
      - NODE_ID=3
      - PEER_ADDRESSES=node1:50051,node2:50052,node4:50054,node5:50055
    ports:
      - "50053:50053"

  node4:
    build: .
    environment:
      - NODE_ID=4
      - PEER_ADDRESSES=node1:50051,node2:50052,node3:50053,node5:50055
    ports:
      - "50054:50054"

  node5:
    build: .
    environment:
      - NODE_ID=5
      - PEER_ADDRESSES=node1:50051,node2:50052,node3:50053,node4:50054
    ports:
      - "50055:50055"
