version: '3.8'
services:
  node1:
    build: .
    environment:
      - NODE_ID=1
    ports:
      - "50051:50051"

  node2:
    build: .
    environment:
      - NODE_ID=2
    ports:
      - "50052:50052"

  node3:
    build: .
    environment:
      - NODE_ID=3
    ports:
      - "50053:50053"

  node4:
    build: .
    environment:
      - NODE_ID=4
    ports:
      - "50054:50054"

  node5:
    build: .
    environment:
      - NODE_ID=5
    ports:
      - "50055:50055"
